apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: lokitheshady/stat-tracker-gateway:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
          env:
            - name: STATAPI_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: statapiurl
            - name: USERAPI_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: userapiurl
            - name: AUTHAPI_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: authapiurl

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
